# @package dataset.SOr_left_ukb_morpho
dataset_name: SOr_left_ukb_morpho
pickle_normal: ${dataset_folder}/UkBioBank/crops/2mm/S.Or./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/UkBioBank/crops/2mm/S.Or./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/UkBioBank/crops/2mm/S.Or./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/UkBioBank/crops/2mm/S.Or./mask/Lcrops
foldlabel_dir: ${dataset_folder}/UkBioBank/crops/2mm/S.Or./mask/Llabels
foldlabel_all: ${dataset_folder}/UkBioBank/crops/2mm/S.Or./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/UkBioBank/crops/2mm/S.Or./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/UkBioBank/crops/2mm/S.Or./mask/Ldistbottom
distbottom_all: ${dataset_folder}/UkBioBank/crops/2mm/S.Or./mask/Ldistbottom.npy
subjects_distbottom_all: ${dataset_folder}/UkBioBank/crops/2mm/S.Or./mask/Ldistbottom_subject.csv
extremity_dir: ${dataset_folder}/UkBioBank/crops/2mm/S.Or./mask/Lextremities
extremity_all: ${dataset_folder}/UkBioBank/crops/2mm/S.Or./mask/Lextremities.npy
subjects_extremity_all: ${dataset_folder}/UkBioBank/crops/2mm/S.Or./mask/Lextremities_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark:
train_val_csv_file: ${dataset_folder}/UkBioBank/subjects_full.csv
subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/sulcal_morphometry/UKB_21045_S.C.sylvian._left.csv ## TO CHANGE !!
subject_column_name: 'Subject'
cutin_mask_path:
cutout_mask_path:
flip_dataset: False
input_size: (1, 30, 38, 22)