# @package dataset.STs_right_isomap
dataset_name: STs_right_isomap
numpy_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/S.T.s./mask/Rskeleton.npy
subjects_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/S.T.s./mask/Rskeleton_subject.csv
foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/S.T.s./mask/Rlabel.npy
subjects_foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/S.T.s./mask/Rlabel_subject.csv
crop_dir: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/datasets/hcp/crops/2mm/S.T.s./mask/Rcrops
crop_file_suffix: _cropped_skeleton.nii.gz
foldlabel_dir: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/S.T.s./mask/Rlabels
pickle_benchmark: 
train_val_csv_file: /neurospin/dico/data/deep_folding/current/datasets/hcp/hcp_isomap_subjects.csv
subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/hcp/hcp_isomap_labels_STs_right.csv
subject_column_name: 'Subject'
cutout_mask_path:
cutin_mask_path:
flip_dataset: False
input_size: (1, 24, 52, 51)