# @package _global_
apply_augmentations: True
random_choice: False
mixed: False
foldlabel: False
trimdepth: True
fill_value: 0
max_angle: 6
max_distance: 6
max_translation: 1
checkerboard_size: 4
keep_extremity: 'top'
uniform_trim: False
binary_trim: True
sigma_noise: 0.2  # set to positive to allow noise
