# @package dataset.SOr_left_40k
dataset_name: SOr_left_40k
pickle_normal: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/S.Or./mask/Lskeleton.pkl
numpy_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/S.Or./mask/Lskeleton.npy
subjects_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/S.Or./mask/Lskeleton_subject.csv
crop_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/S.Or./mask/Lcrops
foldlabel_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/S.Or./mask/Llabels
foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/S.Or./mask/Llabel.npy
subjects_foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/S.Or./mask/Llabel_subject.csv
distbottom_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/S.Or./mask/Ldistbottom
distbottom_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/S.Or./mask/Ldistbottom.npy
extremity_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/S.Or./mask/Lextremities
extremity_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/S.Or./mask/Lextremities.npy
subjects_extremity_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/S.Or./mask/Lextremities_subject.csv
subjects_distbottom_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/S.Or./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/S.Or./mask/Lskeleton_subject.csv
subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/S.Or./mask/Lskeleton_subject.csv # no label
subject_column_name: 'Subject'
cutout_mask_path:
cutin_mask_path:
flip_dataset: False
input_size: (1, 30, 38, 22)