# @package dataset.FColl-SRh_left
dataset_name: FColl-SRh_left
pickle_normal: ${dataset_folder}/ACCpatterns/crops/2mm/F.Coll.-S.Rh./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/ACCpatterns/crops/2mm/F.Coll.-S.Rh./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/ACCpatterns/crops/2mm/F.Coll.-S.Rh./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/ACCpatterns/crops/2mm/F.Coll.-S.Rh./mask/Lcrops
foldlabel_dir: ${dataset_folder}/ACCpatterns/crops/2mm/F.Coll.-S.Rh./mask/Llabels
foldlabel_all: ${dataset_folder}/ACCpatterns/crops/2mm/F.Coll.-S.Rh./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/ACCpatterns/crops/2mm/F.Coll.-S.Rh./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/ACCpatterns/crops/2mm/F.Coll.-S.Rh./mask/Ldistbottom
distbottom_all: ${dataset_folder}/ACCpatterns/crops/2mm/F.Coll.-S.Rh./mask/Ldistbottom.npy
extremity_dir: ${dataset_folder}/ACCpatterns/crops/2mm/F.Coll.-S.Rh./mask/Lextremities
extremity_all: ${dataset_folder}/ACCpatterns/crops/2mm/F.Coll.-S.Rh./mask/Lextremities.npy
subjects_extremity_all: ${dataset_folder}/ACCpatterns/crops/2mm/F.Coll.-S.Rh./mask/Lextremities_subject.csv
subjects_distbottom_all: ${dataset_folder}/ACCpatterns/crops/2mm/F.Coll.-S.Rh./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark:
#train_csv_file: ${dataset_folder}/ACCpatterns/splits/Right/train_split.csv
#val_csv_file: ${dataset_folder}/ACCpatterns/splits/Right/val_split.csv
#test_csv_file: ${dataset_folder}/ACCpatterns/splits/Right/test_split.csv
train_val_csv_file: ${dataset_folder}/ACCpatterns/splits/Right/union/fake_train_val.csv
test_csv_file: ${dataset_folder}/ACCpatterns/splits/Right/union/union_custom_splits_train_val.csv
subject_labels_file: ${dataset_folder}/ACCpatterns/subjects_labels.csv
subject_column_name: 'long_name'
cutout_mask_path:
cutin_mask_path: ${dataset_folder}/ACCpatterns/crops/2mm/F.Coll.-S.Rh./mask/Lmask.npy
flip_dataset: False
input_size: (1, 29, 62, 36)