# @package dataset.cingulate_UKB_right_1-5mm_dilation_5vx
dataset_name: cingulate_UKB_right_1-5mm_dilation_5vx
pickle_normal: /volatile/jl277509/data/UkBioBank/crops/1.5mm_dilation_5vx/CINGULATE/mask/Rskeleton.pkl
numpy_all: /volatile/jl277509/data/UkBioBank/crops/1.5mm_dilation_5vx/CINGULATE/mask/Rskeleton.npy
subjects_all: /volatile/jl277509/data/UkBioBank/crops/1.5mm_dilation_5vx/CINGULATE/mask/Rskeleton_subject.csv
crop_dir: /volatile/jl277509/data/UkBioBank/crops/1.5mm_dilation_5vx/CINGULATE/mask/Rcrops
foldlabel_dir: /volatile/jl277509/data/UkBioBank/crops/1.5mm_dilation_5vx/CINGULATE/mask/Rlabels
foldlabel_all: /volatile/jl277509/data/UkBioBank/crops/1.5mm_dilation_5vx/CINGULATE/mask/Rlabel.npy
subjects_foldlabel_all: /volatile/jl277509/data/UkBioBank/crops/1.5mm_dilation_5vx/CINGULATE/mask/Rlabel_subject.csv
distbottom_dir: /volatile/jl277509/data/UkBioBank/crops/1.5mm_dilation_5vx/CINGULATE/mask/Rdistbottom
distbottom_all: /volatile/jl277509/data/UkBioBank/crops/1.5mm_dilation_5vx/CINGULATE/mask/Rdistbottom.npy
subjects_distbottom_all: /volatile/jl277509/data/UkBioBank/crops/1.5mm_dilation_5vx/CINGULATE/mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark:
train_val_csv_file: /volatile/jl277509/data/UkBioBank/subjects_full.csv
subject_labels_file: /volatile/jl277509/data/UkBioBank/participants_labels.csv
subject_column_name: 'Subject'
input_size: (1, 19, 44, 43)

