# @package dataset.SC-SPoC_right
dataset_name: SC-SPoC_right
pickle_normal: ${dataset_folder}/aggregate_autism/crops/2mm/S.C.-S.Po.C./mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/aggregate_autism/crops/2mm/S.C.-S.Po.C./mask/Rskeleton.npy
subjects_all: ${dataset_folder}/aggregate_autism/crops/2mm/S.C.-S.Po.C./mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/aggregate_autism/crops/2mm/S.C.-S.Po.C./mask/Rcrops
foldlabel_dir: ${dataset_folder}/aggregate_autism/crops/2mm/S.C.-S.Po.C./mask/Rlabels
foldlabel_all: ${dataset_folder}/aggregate_autism/crops/2mm/S.C.-S.Po.C./mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/aggregate_autism/crops/2mm/S.C.-S.Po.C./mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/aggregate_autism/crops/2mm/S.C.-S.Po.C./mask/Rdistbottom
distbottom_all: ${dataset_folder}/aggregate_autism/crops/2mm/S.C.-S.Po.C./mask/Rdistbottom.npy
extremity_dir: ${dataset_folder}/aggregate_autism/crops/2mm/S.C.-S.Po.C./mask/Rextremities
extremity_all: ${dataset_folder}/aggregate_autism/crops/2mm/S.C.-S.Po.C./mask/Rextremities.npy
subjects_extremity_all: ${dataset_folder}/aggregate_autism/crops/2mm/S.C.-S.Po.C./mask/Rextremities_subject.csv
subjects_distbottom_all: ${dataset_folder}/aggregate_autism/crops/2mm/S.C.-S.Po.C./mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark:
train_val_csv_file: ${dataset_folder}/aggregate_autism/all_subjects.csv
subject_labels_file: ${dataset_folder}/aggregate_autism/fake_labels.csv
subject_column_name: 'Subject'
cutout_mask_path:
cutin_mask_path:
flip_dataset: False
input_size: (1, 42, 43, 49)