# @package dataset.OCCIPITAL_left
dataset_name: OCCIPITAL_left
pickle_normal: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/OCCIPITAL/mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/OCCIPITAL/mask/Lskeleton.npy
subjects_all: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/OCCIPITAL/mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/OCCIPITAL/mask/Lcrops
foldlabel_dir: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/OCCIPITAL/mask/Llabels
foldlabel_all: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/OCCIPITAL/mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/OCCIPITAL/mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/OCCIPITAL/mask/Ldistbottom
distbottom_all: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/OCCIPITAL/mask/Ldistbottom.npy
extremity_dir: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/OCCIPITAL/mask/Lextremities
extremity_all: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/OCCIPITAL/mask/Lextremities.npy
subjects_extremity_all: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/OCCIPITAL/mask/Lextremities_subject.csv
subjects_distbottom_all: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/OCCIPITAL/mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark:
train_val_csv_file: ${dataset_folder}/aggregate_schizophrenia/all_subjects.csv
subject_labels_file: ${dataset_folder}/aggregate_schizophrenia/fake_labels.csv
subject_column_name: 'participant_id'
cutout_mask_path:
cutin_mask_path:
flip_dataset: False
input_size: (1, 35, 28, 42)