# @package dataset.ScCal-SLi_right
dataset_name: ScCal-SLi_right
pickle_normal: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/Sc.Cal.-S.Li./mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/Sc.Cal.-S.Li./mask/Rskeleton.npy
subjects_all: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/Sc.Cal.-S.Li./mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/Sc.Cal.-S.Li./mask/Rcrops
foldlabel_dir: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/Sc.Cal.-S.Li./mask/Rlabels
foldlabel_all: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/Sc.Cal.-S.Li./mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/Sc.Cal.-S.Li./mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/Sc.Cal.-S.Li./mask/Rdistbottom
distbottom_all: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/Sc.Cal.-S.Li./mask/Rdistbottom.npy
extremity_dir: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/Sc.Cal.-S.Li./mask/Rextremities
extremity_all: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/Sc.Cal.-S.Li./mask/Rextremities.npy
subjects_extremity_all: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/Sc.Cal.-S.Li./mask/Rextremities_subject.csv
subjects_distbottom_all: ${dataset_folder}/aggregate_schizophrenia/crops/2mm/Sc.Cal.-S.Li./mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark:
train_val_csv_file: ${dataset_folder}/aggregate_schizophrenia/all_subjects.csv
subject_labels_file: ${dataset_folder}/aggregate_schizophrenia/fake_labels.csv
subject_column_name: 'participant_id'
cutout_mask_path:
cutin_mask_path:
flip_dataset: False
input_size: (1, 26, 42, 44)