dataset_name: SFinf-BROCA-SPeCinf_right_UKB_sparse_load_5000
pickle_normal: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.F.inf.-BROCA-S.Pe.C.inf./mask/Rskeleton.pkl
coords_all: /volatile/jl277509/data/UkBioBank/crops/2mm/S.F.inf.-BROCA-S.Pe.C.inf./mask/Rskeleton_sparse/coords
numpy_all: /volatile/jl277509/data/UkBioBank/crops/2mm/S.F.inf.-BROCA-S.Pe.C.inf./mask/Rskeleton_sparse/skeleton
subjects_all: /volatile/jl277509/data/UkBioBank/R_subjects_header_5000.csv
crop_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.F.inf.-BROCA-S.Pe.C.inf./mask/Rcrops
foldlabel_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.F.inf.-BROCA-S.Pe.C.inf./mask/Rlabels
foldlabel_all: /volatile/jl277509/data/UkBioBank/crops/2mm/S.F.inf.-BROCA-S.Pe.C.inf./mask/Rskeleton_sparse/foldlabel
subjects_foldlabel_all: /volatile/jl277509/data/UkBioBank/R_subjects_header_5000.csv
distbottom_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.F.inf.-BROCA-S.Pe.C.inf./mask/Rdistbottom
distbottom_all: /volatile/jl277509/data/UkBioBank/crops/2mm/S.F.inf.-BROCA-S.Pe.C.inf./mask/Rskeleton_sparse/distbottom
subjects_distbottom_all: /volatile/jl277509/data/UkBioBank/R_subjects_header_5000.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: null
train_val_csv_file: /volatile/jl277509/data/UkBioBank/R_subjects_5000.csv
subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/participants.csv
subject_column_name: participant_id
input_size: (1, 26, 40, 43)
