# @package dataset.FIP_right_1000
dataset_name: FIP_right_1000
pickle_normal: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Rskeleton.npy
subjects_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Rcrops
foldlabel_dir: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Rlabels
foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Rdistbottom
distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Rdistbottom.npy
extremity_dir: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Rextremities
extremity_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Rextremities.npy
subjects_extremity_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Rextremities_subject.csv
subjects_distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_csv_file: ${dataset_folder}/UkBioBank40/1000_subjects.csv
val_csv_file: ${dataset_folder}/UkBioBank40/400_subjects_validation.csv
subject_labels_file: ${dataset_folder}/UkBioBank40/participants_sex_age.csv
subject_column_name: 'Subject'
cutout_mask_path:
cutin_mask_path: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Rmask.npy
flip_dataset: False
input_size: (1, 39, 45, 44)