# @package dataset.SC_SPeC_right.yaml
dataset_name: SC_SPeC_right
pickle_normal: ${dataset_folder}/schiz/crops/2mm/S.C.-S.Pe.C./mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/schiz/crops/2mm/S.C.-S.Pe.C./mask/Rskeleton.npy
subjects_all: ${dataset_folder}/schiz/crops/2mm/S.C.-S.Pe.C./mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/schiz/crops/2mm/S.C.-S.Pe.C./mask/Rcrops
foldlabel_dir: ${dataset_folder}/schiz/crops/2mm/S.C.-S.Pe.C./mask/Rlabels
foldlabel_all: ${dataset_folder}/schiz/crops/2mm/S.C.-S.Pe.C./mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/schiz/crops/2mm/S.C.-S.Pe.C./mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/schiz/crops/2mm/S.C.-S.Pe.C./mask/Rdistbottom
distbottom_all: ${dataset_folder}/schiz/crops/2mm/S.C.-S.Pe.C./mask/Rdistbottom.npy
subjects_distbottom_all: ${dataset_folder}/schiz/crops/2mm/S.C.-S.Pe.C./mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
train_csv_file: ${dataset_folder}/schiz/aymeric_stratification/with_sub/train_subjects.csv
val_csv_file: ${dataset_folder}/schiz/aymeric_stratification/with_sub/val_subjects.csv
test_intra_csv_file: ${dataset_folder}/schiz/aymeric_stratification/with_sub/test_intra_subjects.csv
test_csv_file: ${dataset_folder}/schiz/aymeric_stratification/with_sub/test_subjects.csv
subject_labels_file: ${dataset_folder}/schiz/aymeric_stratification/with_sub/used_schiz_subjects.csv
subject_column_name: 'participant_id'
input_size: (1, 42, 47, 51)

