# @package dataset.orbital_left_site_effect_ukb_hcp_2mm
dataset_name: orbital_left_site_effect_ukb_hcp_2mm
numpy_all: /neurospin/dico/data/deep_folding/current/datasets/site_effect_ukb_hcp/crops/2mm/ORBITAL/mask/Lskeleton.npy
subjects_all: /neurospin/dico/data/deep_folding/current/datasets/site_effect_ukb_hcp/crops/2mm/ORBITAL/mask/Lskeleton_subject.csv
foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/site_effect_ukb_hcp/crops/2mm/ORBITAL/mask/Llabel.npy
subjects_foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/site_effect_ukb_hcp/crops/2mm/ORBITAL/mask/Llabel_subject.csv
crop_dir: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/datasets/site_effect_ukb_hcp/crops/2mm/ORBITAL/mask/Lcrops
crop_file_suffix: _cropped_skeleton.nii.gz
foldlabel_dir: /neurospin/dico/data/deep_folding/current/datasets/site_effect_ukb_hcp/crops/2mm/ORBITAL/mask/Llabels
pickle_benchmark: 
train_val_csv_file: /neurospin/dico/data/deep_folding/current/datasets/site_effect_ukb_hcp/subjects.csv
test_csv_file: /neurospin/dico/data/deep_folding/current/datasets/site_effect_ukb_hcp/subjects.csv
#test_csv_file: /neurospin/dico/data/deep_folding/current/datasets/site_effect_ukb_hcp/site_effect_ukb_hcp_1_test_without_headers.csv
#splits_basedir: /neurospin/dico/data/deep_folding/current/datasets/site_effect_ukb_hcp/site_effect_ukb_hcp_subjects_train_split_
subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/site_effect_ukb_hcp/labels.csv
subject_column_name: 'Subject'
input_size: (1, 30, 38, 22)