# @package _global_
batch_size: 32
pin_mem: True
lr: 0.0004
weight_decay: 5.0e-05
max_epochs: 251
nb_epochs_per_saving: 1
nb_epochs_per_tSNE: -1
nb_epochs_per_matrix_plot: 10
nb_epochs_per_weight_save: 10
nb_steps_per_flush_logs: 1
log_every_n_steps: 2
early_stopping_patience: 15
diff_auc_threshold: 0.4  # early stopping too
start_epoch: 0
checkpoint_path:
analysis_path: 
verbose: 1
checking: False
# Data split and subject choice
seed: 1
partition: [0.9, 0.1]
nb_subjects: -1
random: False
random_state: 25
# Parameters of step scheduler
scheduler: False
step_size: 10
gamma: 1.0
class_weights: [1., 1.]
