# @package _global_
dataset_name: FIP_right_UKB
data_dir: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Rskeleton.npy
subject_dir: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Rskeleton_subject.csv
in_shape: [1, 39, 45, 44]
subjects_to_remove: ${dataset_folder}/UkBioBank40/CSLabel/interrupted_CS_QC.csv
remove_subjects: False