# @package _global_
dataset_name: SC-sylv_left_UKB
data_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Lskeleton.npy
subject_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Lskeleton_subject.csv
in_shape: [1, 38, 36, 49]
subjects_to_remove: ${dataset_folder}/UkBioBank40/CSLabel/interrupted_CS_QC.csv
remove_subjects: False