# @package _global_
resize: False
both: True
apply_augmentations: True
foldlabel: True
patch_size: [1, 7, 17, 16]
fill_value: 0
max_angle: 6
checkerboard_size: 4
keep_bottom: True
percentage: 40
variable_percentage: True
