# @package _global_
apply_augmentations: True
random_choice: False
mixed: False
foldlabel: False
trimdepth: False
cropresize: True
fill_value: 0
max_translation: 1
proba_translation: 1
proba_cropresize: 0.8
crop_ratio: [40,100]
