# @package dataset.ORBITAL_right
dataset_name: ORBITAL_right
pickle_normal: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Rskeleton.npy
subjects_all: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Rcrops
foldlabel_dir: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Rlabels
foldlabel_all: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Rdistbottom
distbottom_all: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Rdistbottom.npy
extremity_dir: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Rextremities
extremity_all: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Rextremities.npy
subjects_extremity_all: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Rextremities_subject.csv
subjects_distbottom_all: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/hcp/full_subjects.csv
subject_labels_file: ${dataset_folder}/hcp/participants.csv
subject_column_name: 'Subject'
cutout_mask_path:
cutin_mask_path: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Rmask.npy
flip_dataset: False
input_size: (1, 26, 34, 23)