# @package dataset.ORBITAL_left
dataset_name: ORBITAL_left
pickle_normal: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Lskeleton.npy
subjects_all: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Lcrops
foldlabel_dir: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Llabels
foldlabel_all: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Ldistbottom
distbottom_all: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Ldistbottom.npy
extremity_dir: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Lextremities
extremity_all: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Lextremities.npy
subjects_extremity_all: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Lextremities_subject.csv
subjects_distbottom_all: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/hcp/full_subjects.csv
subject_labels_file: ${dataset_folder}/hcp/participants.csv
subject_column_name: 'Subject'
cutout_mask_path:
cutin_mask_path: ${dataset_folder}/hcp/crops/2mm/ORBITAL/mask/Lmask.npy
flip_dataset: False
input_size: (1, 30, 38, 22)