# @package dataset.FIP_right_UKB40_sparse_load
dataset_name: FIP_right_UKB40_sparse_load
pickle_normal: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/F.I.P./mask/Rskeleton.pkl
coords_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./sparse_load/R/coords
numpy_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./sparse_load/R/skeleton
subjects_all: ${dataset_folder}/UkBioBank40/R_subjects_header.csv
crop_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/F.I.P./mask/Rcrops
foldlabel_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/F.I.P./mask/Rlabels
foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./sparse_load/R/foldlabel
subjects_foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/F.I.P./mask/Rlabel_subject.csv
distbottom_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/F.I.P./mask/Rdistbottom
distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./sparse_load/R/distbottom
subjects_distbottom_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/F.I.P./sparse_load/R/Rdistbottom_subject.csv
extremity_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/F.I.P./mask/Rextremities
extremity_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./sparse_load/R/extremities
subjects_extremity_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/crops/2mm/F.I.P./sparse_load/R/Rextremities_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: null
train_val_csv_file: ${dataset_folder}/UkBioBank40/R_subjects.csv
subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank40/participants_labels.csv # doesn't exist
subject_column_name: Subject
mask_path: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./Rmask.npy
flip_dataset: True
input_size: (1, 39, 45, 44)