# @package dataset.STs_left
dataset_name: STs_left
pickle_normal: ${dataset_folder}/aggregate_bipolar/crops/2mm/S.T.s./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/aggregate_bipolar/crops/2mm/S.T.s./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/aggregate_bipolar/crops/2mm/S.T.s./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/aggregate_bipolar/crops/2mm/S.T.s./mask/Lcrops
foldlabel_dir: ${dataset_folder}/aggregate_bipolar/crops/2mm/S.T.s./mask/Llabels
foldlabel_all: ${dataset_folder}/aggregate_bipolar/crops/2mm/S.T.s./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/aggregate_bipolar/crops/2mm/S.T.s./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/aggregate_bipolar/crops/2mm/S.T.s./mask/Ldistbottom
distbottom_all: ${dataset_folder}/aggregate_bipolar/crops/2mm/S.T.s./mask/Ldistbottom.npy
extremity_dir: ${dataset_folder}/aggregate_bipolar/crops/2mm/S.T.s./mask/Lextremities
extremity_all: ${dataset_folder}/aggregate_bipolar/crops/2mm/S.T.s./mask/Lextremities.npy
subjects_extremity_all: ${dataset_folder}/aggregate_bipolar/crops/2mm/S.T.s./mask/Lextremities_subject.csv
subjects_distbottom_all: ${dataset_folder}/aggregate_bipolar/crops/2mm/S.T.s./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark:
train_val_csv_file: ${dataset_folder}/aggregate_bipolar/all_subjects.csv
subject_labels_file: ${dataset_folder}/aggregate_bipolar/fake_labels.csv
subject_column_name: 'Subject'
cutout_mask_path:
cutin_mask_path:
flip_dataset: False
input_size: (1, 25, 55, 50)