#!/bin/bash
#PBS -q kraken
#PBS -l walltime=80:00:00
#PBS -l ncpus=20
#PBS -l ngpus=2
#PBS -l mem=80g

cd /neurospin/dico/babdelghani/Runs/02_champollion_v1/Program
source venv_kraken/bin/activate
cd /neurospin/dico/babdelghani/Runs/02_champollion_v1/Program/2023_jlaval_STSbabies/contrastive

python3 train.py sigma_labels=0.01 batch_size=16,32,64,128 backbone_output_size=256 proj_layers_shapes=[256,256,256,256] -m
