# @package dataset.fissure_lateral_HCP_stratified_extreme_Flanker_left
dataset_name: fissure_lateral_HCP_stratified_extreme_Flanker_left
pickle_normal: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/crops/2mm/F.C.L.p.-subsc.-F.C.L.a.-INSULA./mask/Lskeleton.pkl
numpy_all: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/crops/2mm/F.C.L.p.-subsc.-F.C.L.a.-INSULA./mask/Lskeleton.npy
subjects_all: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/crops/2mm/F.C.L.p.-subsc.-F.C.L.a.-INSULA./mask/Lskeleton_subject.csv
crop_dir: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/crops/2mm/F.C.L.p.-subsc.-F.C.L.a.-INSULA./mask/Lcrops
foldlabel_dir: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/crops/2mm/F.C.L.p.-subsc.-F.C.L.a.-INSULA./mask/Llabels
foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/crops/2mm/F.C.L.p.-subsc.-F.C.L.a.-INSULA./mask/Llabel.npy
subjects_foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/crops/2mm/F.C.L.p.-subsc.-F.C.L.a.-INSULA./mask/Llabel_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_csv_file: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/extreme_flanker_train_subjects.csv
val_csv_file: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/extreme_flanker_val_subjects.csv
test_csv_file: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/extreme_flanker_test_subjects.csv
# subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/hcp/participants_age_continuous.csv
subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/participants.csv
subject_column_name: 'Subject'
label_scaling:
input_size: (1, 39, 67, 53)
