# @package dataset.deMatos_polar_left
dataset_name: deMatos_polar_left
pickle_normal: ${dataset_folder}/UkBioBank40/crops/2mm/deMatos_polar./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/UkBioBank40/crops/2mm/deMatos_polar./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/UkBioBank40/crops/2mm/deMatos_polar./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/UkBioBank40/crops/2mm/deMatos_polar./mask/Lcrops
foldlabel_dir: ${dataset_folder}/UkBioBank40/crops/2mm/deMatos_polar./mask/Llabels
foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/deMatos_polar./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/deMatos_polar./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/UkBioBank40/crops/2mm/deMatos_polar./mask/Ldistbottom
distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/deMatos_polar./mask/Ldistbottom.npy
extremity_dir: ${dataset_folder}/UkBioBank40/crops/2mm/deMatos_polar./mask/Lextremities
extremity_all: ${dataset_folder}/UkBioBank40/crops/2mm/deMatos_polar./mask/Lextremities.npy
subjects_extremity_all: ${dataset_folder}/UkBioBank40/crops/2mm/deMatos_polar./mask/Lextremities_subject.csv
subjects_distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/deMatos_polar./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/UkBioBank40/crops/2mm/deMatos_polar./mask/Lskeleton_subject.csv
subject_labels_file: ${dataset_folder}/UkBioBank40/participants_sex_age.csv
subject_column_name: 'Subject'
cutout_mask_path:
cutin_mask_path: ${dataset_folder}/UkBioBank40/crops/2mm/deMatos_polar./mask/Lmask.npy
flip_dataset: False
input_size: (1, 41, 69, 38)