# @package dataset.SC-sylv_left_UKB40
dataset_name: SC-sylv_left_UKB40
pickle_normal: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Lcrops
foldlabel_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Llabels
foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Ldistbottom
distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Ldistbottom.npy
extremity_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Lextremities
extremity_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Lextremities.npy
subjects_extremity_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Lextremities_subject.csv
subjects_distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
# train_val_csv_file: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Lskeleton_subject.csv
train_csv_file: ${dataset_folder}/UkBioBank40/crops/2mm/LARGE_CINGULATE./mask/Rskeleton_subject_train.csv
val_csv_file: ${dataset_folder}/UkBioBank40/crops/2mm/LARGE_CINGULATE./mask/Rskeleton_subject_val.csv
test_csv_file: ${dataset_folder}/UkBioBank40/crops/2mm/LARGE_CINGULATE./mask/Rskeleton_subject_test.csv
subject_labels_file: ${dataset_folder}//UkBioBank40/log_thickness_surface_Age.csv
subject_column_name: 'participant_id'
# subject_labels_file: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Lskeleton_subject.csv # no label
# subject_column_name: 'Subject'
cutout_mask_path:
cutin_mask_path: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Lmask.npy
flip_dataset: False
input_size: (1, 38, 36, 49)
