# @package dataset.big_cingulate_HCP_stratified_right
dataset_name: big_cingulate_HCP_stratified_right
pickle_normal: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/crops/2mm/BIG_CINGULATE/mask/Rskeleton.pkl
numpy_all: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/crops/2mm/BIG_CINGULATE/mask/Rskeleton.npy
subjects_all: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/crops/2mm/BIG_CINGULATE/mask/Rskeleton_subject.csv
crop_dir: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/crops/2mm/BIG_CINGULATE/mask/Rcrops
foldlabel_dir: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/crops/2mm/BIG_CINGULATE/mask/Rlabels
foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/crops/2mm/BIG_CINGULATE/mask/Rlabel.npy
subjects_foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/crops/2mm/BIG_CINGULATE/mask/Rlabel_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_csv_file: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/train_subjects.csv
val_csv_file: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/val_subjects.csv
test_csv_file: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/test_subjects.csv
# subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/hcp/participants_age_continuous.csv
subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/participants.csv
subject_column_name: 'Subject'
input_size: (1, 17, 67, 54)