# @package dataset.big_cingulate_ACCpatterns_left
dataset_name: big_cingulate_ACCpatterns_left
numpy_all: /neurospin/dico/data/deep_folding/current/datasets/ACCpatterns/crops/2mm/BIG_CINGULATE/mask/Lskeleton.npy
subjects_all: /neurospin/dico/data/deep_folding/current/datasets/ACCpatterns/crops/2mm/BIG_CINGULATE/mask/Lskeleton_subject.csv
foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/ACCpatterns/crops/2mm/BIG_CINGULATE/mask/Llabel.npy
subjects_foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/ACCpatterns/crops/2mm/BIG_CINGULATE/mask/Llabel_subject.csv
crop_dir: /neurospin/dico/data/deep_folding/current/datasets/ACCpatterns/crops/2mm/BIG_CINGULATE/mask/Lcrops
crop_file_suffix: _cropped_skeleton.nii.gz
foldlabel_dir: /neurospin/dico/data/deep_folding/current/datasets/ACCpatterns/crops/2mm/BIG_CINGULATE/mask/Llabels
pickle_benchmark: 
train_val_csv_file: /neurospin/dico/data/deep_folding/current/datasets/ACCpatterns/train_val_ACCpatterns.csv
subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/ACCpatterns/subjects_labels.csv
subject_column_name: 'long_name'
input_size: (1, 19, 68, 56)