# @package dataset.cingulate_Utrecht
dataset_name: cingulate_Utrecht
pickle_normal: /neurospin/dico/data/deep_folding/current/datasets/utrecht_40wks/crops/2mm/F.C.M.ant./mask/Rskeleton.pkl
#beware: subjects all are only the test subjects ? (SVM)
numpy_all: /neurospin/dico/data/deep_folding/current/datasets/utrecht_40wks/crops/2mm/F.C.M.ant./mask/Rskeleton.npy
#beware: subjects all are only the test subjects ? (SVM)
subjects_all: /neurospin/dico/data/deep_folding/current/datasets/utrecht_40wks/crops/2mm/F.C.M.ant./mask/Rskeleton_subject.csv
crop_dir: /neurospin/dico/data/deep_folding/current/datasets/utrecht_40wks/crops/2mm/F.C.M.ant./mask/Rcrops
foldlabel_dir: /neurospin/dico/data/deep_folding/current/datasets/utrecht_40wks/crops/2mm/F.C.M.ant./mask/Rlabels
foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/utrecht_40wks/crops/2mm/F.C.M.ant./mask/Rlabel.npy
subjects_foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/utrecht_40wks/crops/2mm/F.C.M.ant./mask/Rlabel_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
#train_val complementary to test file (SVM)
train_val_csv_file: /neurospin/dico/data/deep_folding/current/datasets/utrecht_40wks/crops/2mm/F.C.M.ant./mask/Rskeleton_subject.csv
subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/utrecht_40wks/crops/2mm/F.C.M.ant./mask/fake_labels.csv
subject_column_name: 'Subject'
n_max: 1080
