# @package _global_
output_dir: ../../../Output
sweep_day: ${now:%Y-%m-%d}
suffix_dir: ""
sweep_dir: ${output_dir}/${sweep_day}${suffix_dir}
run_time: ${now:%H-%M-%S}
hydra:
  job:
    chdir: True
  run:
    dir: ${sweep_dir}/${run_time}_${get_train_seed:}
  sweep:
    dir: ${sweep_dir}
    subdir: ${run_time}_${hydra.job.num}
checkpoint_dir: output_dir
