# @package _global_
# Characterization of the ConvNet model used
backbone_name: convnext
depth: [3,3,9,3]
dims: [32,64,128,256]
initial_stride: 1
initial_kernel_size: 7
kernel_size: 3
nb_blocks: 4
adaptive_pooling: !!null
#adaptive_pooling: ['average', [3,3,3]]
#original config
#depth: [3,3,9,3]
#dims: [96,192,384,768]
#initial_stride: 4
#initial_kernel_size: 4
#kernel_size: 7
#nb_blocks: 4
#adaptive_pooling: ['average', 1]
backbone_output_size: 32