# @package dataset.occipital_UKB_L
dataset_name: occipital_UKB_L
numpy_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/OCCIPITAL/mask/Lskeleton.npy
subjects_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/OCCIPITAL/mask/Lskeleton_subject.csv
crop_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/OCCIPITAL/mask/Lcrops
foldlabel_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/OCCIPITAL/mask/Llabels
foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/OCCIPITAL/mask/Llabel.npy
subjects_foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/OCCIPITAL/mask/Llabel_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
train_val_csv_file: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/csv/UkBioBank/subjects_full.csv
subject_labels_file: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/csv/UkBioBank/participants.csv
subject_column_name: 'Subject'
input_size: (1, 38, 51, 60)