# @package dataset.orbital_left_PreCatatoes_custom
dataset_name: orbital_left_PreCatatoes_custom
numpy_all: /neurospin/dico/data/deep_folding/current/datasets/PreCatatoes/crops/2mm/S.Or./mask/Lskeleton.npy
subjects_all: /neurospin/dico/data/deep_folding/current/datasets/PreCatatoes/crops/2mm/S.Or./mask/Lskeleton_subject.csv
foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/PreCatatoes/crops/2mm/S.Or./mask/Llabel.npy
subjects_foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/PreCatatoes/crops/2mm/S.Or./mask/Llabel_subject.csv
crop_dir: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/datasets/PreCatatoes/crops/2mm/S.Or./mask/Lcrops
crop_file_suffix: _cropped_skeleton.nii.gz
foldlabel_dir: /neurospin/dico/data/deep_folding/current/datasets/PreCatatoes/crops/2mm/S.Or./mask/Llabels
pickle_benchmark: 
train_val_csv_file: /neurospin/dico/data/deep_folding/current/datasets/orbital_patterns/PreCatatoes/fake_train_val.csv
#test_csv_file: /neurospin/dico/data/deep_folding/current/datasets/PreCatatoes/PreCatatoes_1_test_without_headers.csv
test_csv_file: /neurospin/dico/data/deep_folding/current/datasets/orbital_patterns/PreCatatoes/union_splits.csv
subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/PreCatatoes/PreCatatoes_labels.csv
subject_column_name: 'Subject'
mask_path:
input_size: (1, 30, 38, 22)