# @package dataset.FPO-SCu-ScCal_left
dataset_name: FPO-SCu-ScCal_left
pickle_normal: ${dataset_folder}/hcp/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/hcp/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/hcp/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/hcp/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Lcrops
foldlabel_dir: ${dataset_folder}/hcp/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Llabels
foldlabel_all: ${dataset_folder}/hcp/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/hcp/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/hcp/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Ldistbottom
distbottom_all: ${dataset_folder}/hcp/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Ldistbottom.npy
extremity_dir: ${dataset_folder}/hcp/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Lextremities
extremity_all: ${dataset_folder}/hcp/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Lextremities.npy
subjects_extremity_all: ${dataset_folder}/hcp/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Lextremities_subject.csv
subjects_distbottom_all: ${dataset_folder}/hcp/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
#train_csv_file: ${dataset_folder}/hcp/Isomap/splits/union/train_split.csv
#val_csv_file: ${dataset_folder}/hcp/Isomap/splits/union/val_split.csv
#test_csv_file: ${dataset_folder}/hcp/Isomap/splits/union/test_split.csv
subject_labels_file: ${dataset_folder}/hcp/hcp_OFC_labels.csv
test_csv_file: ${dataset_folder}/hcp/Isomap/splits/union/union_custom_splits_train_val.csv
train_val_csv_file: ${dataset_folder}/hcp/Isomap/splits/union/fake_train_val.csv
subject_labels_file: ${dataset_folder}/hcp/hcp_isomap_labels_SC-sylv_left.csv
subject_column_name: 'Subject'
cutout_mask_path:
cutin_mask_path: ${dataset_folder}/hcp/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Lmask.npy
flip_dataset: False
input_size: (1, 25, 42, 54)