# @package dataset.Lobule_parietal_sup_right
dataset_name: Lobule_parietal_sup_right
pickle_normal: ${dataset_folder}/hcp/crops/2mm/Lobule_parietal_sup./mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/hcp/crops/2mm/Lobule_parietal_sup./mask/Rskeleton.npy
subjects_all: ${dataset_folder}/hcp/crops/2mm/Lobule_parietal_sup./mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/hcp/crops/2mm/Lobule_parietal_sup./mask/Rcrops
foldlabel_dir: ${dataset_folder}/hcp/crops/2mm/Lobule_parietal_sup./mask/Rlabels
foldlabel_all: ${dataset_folder}/hcp/crops/2mm/Lobule_parietal_sup./mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/hcp/crops/2mm/Lobule_parietal_sup./mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/hcp/crops/2mm/Lobule_parietal_sup./mask/Rdistbottom
distbottom_all: ${dataset_folder}/hcp/crops/2mm/Lobule_parietal_sup./mask/Rdistbottom.npy
extremity_dir: ${dataset_folder}/hcp/crops/2mm/Lobule_parietal_sup./mask/Rextremities
extremity_all: ${dataset_folder}/hcp/crops/2mm/Lobule_parietal_sup./mask/Rextremities.npy
subjects_extremity_all: ${dataset_folder}/hcp/crops/2mm/Lobule_parietal_sup./mask/Rextremities_subject.csv
subjects_distbottom_all: ${dataset_folder}/hcp/crops/2mm/Lobule_parietal_sup./mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
#train_csv_file: ${dataset_folder}/hcp/Isomap/splits/union/train_split.csv
#val_csv_file: ${dataset_folder}/hcp/Isomap/splits/union/val_split.csv
#test_csv_file: ${dataset_folder}/hcp/Isomap/splits/union/test_split.csv
subject_labels_file: ${dataset_folder}/hcp/hcp_OFC_labels.csv
test_csv_file: ${dataset_folder}/hcp/Isomap/splits/union/union_custom_splits_train_val.csv
train_val_csv_file: ${dataset_folder}/hcp/Isomap/splits/union/fake_train_val.csv
subject_labels_file: ${dataset_folder}/hcp/hcp_isomap_labels_SC-sylv_left.csv
subject_column_name: 'Subject'
cutout_mask_path:
cutin_mask_path: ${dataset_folder}/hcp/crops/2mm/Lobule_parietal_sup./mask/Rmask.npy
flip_dataset: False
input_size: (1, 41, 45, 48)