# @package dataset.FIP_left
dataset_name: FIP_left
pickle_normal: ${dataset_folder}/hcp/crops/2mm/F.I.P./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/hcp/crops/2mm/F.I.P./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/hcp/crops/2mm/F.I.P./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/hcp/crops/2mm/F.I.P./mask/Lcrops
foldlabel_dir: ${dataset_folder}/hcp/crops/2mm/F.I.P./mask/Llabels
foldlabel_all: ${dataset_folder}/hcp/crops/2mm/F.I.P./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/hcp/crops/2mm/F.I.P./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/hcp/crops/2mm/F.I.P./mask/Ldistbottom
distbottom_all: ${dataset_folder}/hcp/crops/2mm/F.I.P./mask/Ldistbottom.npy
extremity_dir: ${dataset_folder}/hcp/crops/2mm/F.I.P./mask/Lextremities
extremity_all: ${dataset_folder}/hcp/crops/2mm/F.I.P./mask/Lextremities.npy
subjects_extremity_all: ${dataset_folder}/hcp/crops/2mm/F.I.P./mask/Lextremities_subject.csv
subjects_distbottom_all: ${dataset_folder}/hcp/crops/2mm/F.I.P./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/orbital_patterns/Troiani/Left/union/fake_train_val.csv
test_csv_file: ${dataset_folder}/orbital_patterns/Troiani/Left/union/union_custom_splits_train_val.csv
#train_csv_file: ${dataset_folder}/orbital_patterns/Troiani/Left/train_split.csv
#val_csv_file: ${dataset_folder}/orbital_patterns/Troiani/Left/val_split.csv
#test_csv_file: ${dataset_folder}/orbital_patterns/Troiani/Left/test_split.csv
subject_labels_file: ${dataset_folder}/hcp/hcp_OFC_labels.csv
subject_column_name: 'Subject'
cutout_mask_path:
cutin_mask_path: ${dataset_folder}/hcp/crops/2mm/F.I.P./mask/Lmask.npy
flip_dataset: False
input_size: (1, 40, 44, 42)