# @package dataset.STi-STs-STpol_left
dataset_name: STi-STs-STpol_left
pickle_normal: ${dataset_folder}/UkBioBank/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/UkBioBank/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/UkBioBank/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/UkBioBank/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Lcrops
foldlabel_dir: ${dataset_folder}/UkBioBank/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Llabels
foldlabel_all: ${dataset_folder}/UkBioBank/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/UkBioBank/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/UkBioBank/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Ldistbottom
distbottom_all: ${dataset_folder}/UkBioBank/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Ldistbottom.npy
subjects_distbottom_all: ${dataset_folder}/UkBioBank/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/UkBioBank/subjects_full.csv
subject_labels_file: ${dataset_folder}/UkBioBank/participants.csv
subject_column_name: 'participant_id'
input_size: (1, 34, 67, 57)