# @package dataset.Lobule_parietal_sup_right
dataset_name: Lobule_parietal_sup_right
pickle_normal: ${dataset_folder}/UkBioBank40/crops/2mm/Lobule_parietal_sup./mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/UkBioBank40/crops/2mm/Lobule_parietal_sup./mask/Rskeleton.npy
subjects_all: ${dataset_folder}/UkBioBank40/crops/2mm/Lobule_parietal_sup./mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/UkBioBank40/crops/2mm/Lobule_parietal_sup./mask/Rcrops
foldlabel_dir: ${dataset_folder}/UkBioBank40/crops/2mm/Lobule_parietal_sup./mask/Rlabels
foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/Lobule_parietal_sup./mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/Lobule_parietal_sup./mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/UkBioBank40/crops/2mm/Lobule_parietal_sup./mask/Rdistbottom
distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/Lobule_parietal_sup./mask/Rdistbottom.npy
extremity_dir: ${dataset_folder}/UkBioBank40/crops/2mm/Lobule_parietal_sup./mask/Rextremities
extremity_all: ${dataset_folder}/UkBioBank40/crops/2mm/Lobule_parietal_sup./mask/Rextremities.npy
subjects_extremity_all: ${dataset_folder}/UkBioBank40/crops/2mm/Lobule_parietal_sup./mask/Rextremities_subject.csv
subjects_distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/Lobule_parietal_sup./mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/UkBioBank40/crops/2mm/Lobule_parietal_sup./mask/Rskeleton_subject.csv
subject_labels_file: ${dataset_folder}/UkBioBank40/participants_sex_age.csv
subject_column_name: 'Subject'
cutout_mask_path:
cutin_mask_path: ${dataset_folder}/UkBioBank40/crops/2mm/Lobule_parietal_sup./mask/Rmask.npy
flip_dataset: False
input_size: (1, 41, 45, 48)