# @package dataset.SC-sylv_right_ccrdwalk_UKB40
dataset_name: SC-sylv_right_ccrdwalk_UKB40
pickle_normal: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Rccrdwalk.npy
subjects_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Rcrops
foldlabel_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Rlabels
foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Rdistbottom
distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Rdistbottom.npy
extremity_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Rextremities
extremity_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Rextremities.npy
subjects_extremity_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Rextremities_subject.csv
subjects_distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Rskeleton_subject.csv
subject_labels_file: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Rskeleton_subject.csv # no label
subject_column_name: 'Subject'
cutout_mask_path:
cutin_mask_path: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Rmask.npy
flip_dataset: False
input_size: (1, 42, 34, 49)
