# @package dataset.SOr_left_schiz
dataset_name: SOr_left_schiz
numpy_all: /neurospin/dico/data/deep_folding/history/2024-10-schizophrene/datasets/schiz/crops/2mm/S.Or./mask/Lskeleton.npy
subjects_all: /neurospin/dico/data/deep_folding/history/2024-10-schizophrene/datasets/schiz/crops/2mm/S.Or./mask/Lskeleton_subject.csv
foldlabel_all: /neurospin/dico/data/deep_folding/history/2024-10-schizophrene/datasets/schiz/crops/2mm/S.Or./mask/Llabel.npy
subjects_foldlabel_all: /neurospin/dico/data/deep_folding/history/2024-10-schizophrene/datasets/schiz/crops/2mm/S.Or./mask/Llabel_subject.csv
crop_dir: /neurospin/dico/data/deep_folding/history/2024-10-schizophrene/datasets/schiz/crops/2mm/S.Or./mask/Lcrops
crop_file_suffix: _cropped_skeleton.nii.gz
foldlabel_dir: /neurospin/dico/data/deep_folding/history/2024-10-schizophrene/datasets/schiz/crops/2mm/S.Or./mask/Llabels
train_csv_file: /neurospin/dico/data/deep_folding/history/2024-10-schizophrene/datasets/schiz/new_stratification/train_subjects.csv
val_csv_file: /neurospin/dico/data/deep_folding/history/2024-10-schizophrene/datasets/schiz/new_stratification/val_subjects.csv
test_intra_csv_file: /neurospin/dico/data/deep_folding/history/2024-10-schizophrene/datasets/schiz/new_stratification/test_intra_subjects.csv
test_csv_file: /neurospin/dico/data/deep_folding/history/2024-10-schizophrene/datasets/schiz/new_stratification/test_subjects.csv
subject_labels_file: /neurospin/dico/data/deep_folding/history/2024-10-schizophrene/datasets/schiz/used_schiz_subjects.csv
subject_column_name: 'participant_id'
input_size: (1, 30, 38, 22)