# @package dataset.FIP_right
dataset_name: FIP_right
pickle_normal: ${dataset_folder}/UkBioBank/crops/2mm/F.I.P./mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/UkBioBank/crops/2mm/F.I.P./mask/Rskeleton.npy
subjects_all: ${dataset_folder}/UkBioBank/crops/2mm/F.I.P./mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/UkBioBank/crops/2mm/F.I.P./mask/Rcrops
foldlabel_dir: ${dataset_folder}/UkBioBank/crops/2mm/F.I.P./mask/Rlabels
foldlabel_all: ${dataset_folder}/UkBioBank/crops/2mm/F.I.P./mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/UkBioBank/crops/2mm/F.I.P./mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/UkBioBank/crops/2mm/F.I.P./mask/Rdistbottom
distbottom_all: ${dataset_folder}/UkBioBank/crops/2mm/F.I.P./mask/Rdistbottom.npy
extremity_dir: ${dataset_folder}/UkBioBank/crops/2mm/F.I.P./mask/Rextremities
extremity_all: ${dataset_folder}/UkBioBank/crops/2mm/F.I.P./mask/Rextremities.npy
subjects_extremity_all: ${dataset_folder}/UkBioBank/crops/2mm/F.I.P./mask/Rextremities_subject.csv
subjects_distbottom_all: ${dataset_folder}/UkBioBank/crops/2mm/F.I.P./mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/UkBioBank/subjects_full.csv
subject_labels_file: ${dataset_folder}/UkBioBank/participants.csv
subject_column_name: 'participant_id'
input_size: (1, 39, 45, 44)