# @package dataset.STi-STs-STpol_left
dataset_name: STi-STs-STpol_left
pickle_normal: ${dataset_folder}/dHCP_374_subjects/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/dHCP_374_subjects/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/dHCP_374_subjects/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/dHCP_374_subjects/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Lcrops
foldlabel_dir: ${dataset_folder}/dHCP_374_subjects/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Llabels
foldlabel_all: ${dataset_folder}/dHCP_374_subjects/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/dHCP_374_subjects/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/dHCP_374_subjects/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Ldistbottom
distbottom_all: ${dataset_folder}/dHCP_374_subjects/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Ldistbottom.npy
extremity_dir: ${dataset_folder}/dHCP_374_subjects/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Lextremities
extremity_all: ${dataset_folder}/dHCP_374_subjects/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Lextremities.npy
subjects_extremity_all: ${dataset_folder}/dHCP_374_subjects/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Lextremities_subject.csv
subjects_distbottom_all: ${dataset_folder}/dHCP_374_subjects/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/dHCP_374_subjects/all_subjects.csv
subject_labels_file: ${dataset_folder}/dHCP_374_subjects/participants.csv
subject_column_name: 'Subject'
cutout_mask_path:
cutin_mask_path: ${dataset_folder}/dHCP_374_subjects/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Lmask.npy
flip_dataset: False
input_size: (1, 34, 67, 57)