# @package dataset.orbital_left_hcp_custom_cv_1-5mm
dataset_name: orbital_left_hcp_custom_cv_1-5mm
numpy_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/1.5mm/ORBITAL/mask/Lskeleton.npy
subjects_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/1.5mm/ORBITAL/mask/Lskeleton_subject.csv
foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/1.5mm/ORBITAL/mask/Llabel.npy
subjects_foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/1.5mm/ORBITAL/mask/Llabel_subject.csv
crop_dir: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/datasets/hcp/crops/1.5mm/ORBITAL/mask/Lcrops
crop_file_suffix: _cropped_skeleton.nii.gz
foldlabel_dir: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/1.5mm/ORBITAL/mask/Llabels
pickle_benchmark: 
train_val_csv_file: /neurospin/dico/data/deep_folding/current/datasets/hcp/fake_train_val.csv
#test_csv_file: /neurospin/dico/data/deep_folding/current/datasets/hcp/hcp_1_test_without_headers.csv
test_csv_file: /neurospin/dico/data/deep_folding/current/datasets/hcp/union_custom_splits_train_val.csv
#splits_basedir: /neurospin/dico/data/deep_folding/current/datasets/hcp/hcp_subjects_train_split_
subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/hcp/hcp_OFC_labels.csv
subject_column_name: 'Subject'
input_size: (1, 41, 50, 30)