# @package dataset.cingulate_right_UKB_kraken
dataset_name: cingulate_right_UKB_kraken
pickle_normal: /home_local/jl277509/data/datasets/UkBioBank/crops/2mm/CINGULATE/mask/Rskeleton.pkl
numpy_all: /home_local/jl277509/data/datasets/UkBioBank/crops/2mm/CINGULATE/mask/Rskeleton.npy
subjects_all: /home_local/jl277509/data/datasets/UkBioBank/crops/2mm/CINGULATE/mask/Rskeleton_subject.csv
crop_dir: /home_local/jl277509/data/datasets/UkBioBank/crops/2mm/CINGULATE/mask/Rcrops
foldlabel_dir: /home_local/jl277509/data/datasets/UkBioBank/crops/2mm/CINGULATE/mask/Rlabels
foldlabel_all: /home_local/jl277509/data/datasets/UkBioBank/crops/2mm/CINGULATE/mask/Rlabel.npy
subjects_foldlabel_all: /home_local/jl277509/data/datasets/UkBioBank/crops/2mm/CINGULATE/mask/Rlabel_subject.csv
distbottom_dir: /home_local/jl277509/data/datasets/UkBioBank/crops/2mm/CINGULATE/mask/Rdistbottom
distbottom_all: /home_local/jl277509/data/datasets/UkBioBank/crops/2mm/CINGULATE/mask/Rdistbottom.npy
subjects_distbottom_all: /home_local/jl277509/data/datasets/UkBioBank/crops/2mm/CINGULATE/mask/Rdistbottom_subject.csv
extremity_dir: /home_local/jl277509/data/datasets/UkBioBank/crops/2mm/CINGULATE/mask/Rextremities
extremity_all: /home_local/jl277509/data/datasets/UkBioBank/crops/2mm/CINGULATE/mask/Rextremities.npy
subjects_extremity_all: /home_local/jl277509/data/datasets/UkBioBank/crops/2mm/CINGULATE/mask/Rextremities_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark:
train_val_csv_file: /home_local/jl277509/data/datasets/UkBioBank/subjects_full.csv
subject_labels_file: /home_local/jl277509/data/datasets/UkBioBank/participants_labels.csv
subject_column_name: 'Subject'
#input_size: (1, 43, 22, 16) # rotated
input_size: (1, 16, 37, 37)
#input_size: (1, 17, 40, 38) #without reskel