# @package dataset.OCCIPITAL_right
dataset_name: OCCIPITAL_right
pickle_normal: ${dataset_folder}/UkBioBank40/crops/2mm/OCCIPITAL/mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/UkBioBank40/crops/2mm/OCCIPITAL/mask/Rskeleton.npy
subjects_all: ${dataset_folder}/UkBioBank40/crops/2mm/OCCIPITAL/mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/UkBioBank40/crops/2mm/OCCIPITAL/mask/Rcrops
foldlabel_dir: ${dataset_folder}/UkBioBank40/crops/2mm/OCCIPITAL/mask/Rlabels
foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/OCCIPITAL/mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/OCCIPITAL/mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/UkBioBank40/crops/2mm/OCCIPITAL/mask/Rdistbottom
distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/OCCIPITAL/mask/Rdistbottom.npy
extremity_dir: ${dataset_folder}/UkBioBank40/crops/2mm/OCCIPITAL/mask/Rextremities
extremity_all: ${dataset_folder}/UkBioBank40/crops/2mm/OCCIPITAL/mask/Rextremities.npy
subjects_extremity_all: ${dataset_folder}/UkBioBank40/crops/2mm/OCCIPITAL/mask/Rextremities_subject.csv
subjects_distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/OCCIPITAL/mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_csv_file: ${dataset_folder}/UkBioBank40/20000_subjects_set1.csv
val_csv_file: ${dataset_folder}/UkBioBank40/400_subjects_validation.csv
subject_labels_file: ${dataset_folder}/UkBioBank40/participants_sex_age.csv
subject_column_name: 'Subject'
cutout_mask_path:
cutin_mask_path: ${dataset_folder}/UkBioBank40/crops/2mm/OCCIPITAL/mask/Rmask.npy
flip_dataset: False
input_size: (1, 35, 30, 46)