# @package dataset.FIP_left
dataset_name: FIP_left
pickle_normal: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Lcrops
foldlabel_dir: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Llabels
foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Ldistbottom
distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Ldistbottom.npy
extremity_dir: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Lextremities
extremity_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Lextremities.npy
subjects_extremity_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Lextremities_subject.csv
subjects_distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_csv_file: ${dataset_folder}/UkBioBank40/yaware_volume/Lskeleton_subject_train.csv
val_csv_file: ${dataset_folder}/UkBioBank40/yaware_volume/Lskeleton_subject_val.csv
test_csv_file: ${dataset_folder}/UkBioBank40/yaware_volume/Lskeleton_subject_test.csv
subject_labels_file: ${dataset_folder}/UkBioBank40/participants_sex_age_volumes_normalized.csv
subject_column_name: 'participant_id'
cutout_mask_path:
cutin_mask_path: ${dataset_folder}/UkBioBank40/crops/2mm/F.I.P./mask/Lmask.npy
flip_dataset: False
input_size: (1, 40, 44, 42)