# @package dataset.STi-STs-STpol_right
dataset_name: STi-STs-STpol_right
pickle_normal: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Rskeleton.npy
subjects_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Rcrops
foldlabel_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Rlabels
foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Rdistbottom
distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Rdistbottom.npy
extremity_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Rextremities
extremity_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Rextremities.npy
subjects_extremity_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Rextremities_subject.csv
subjects_distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_csv_file: ${dataset_folder}/UkBioBank40/yaware_volume/Rskeleton_subject_train.csv
val_csv_file: ${dataset_folder}/UkBioBank40/yaware_volume/Rskeleton_subject_val.csv
test_csv_file: ${dataset_folder}/UkBioBank40/yaware_volume/Rskeleton_subject_test.csv
subject_labels_file: ${dataset_folder}/UkBioBank40/participants_sex_age_volumes_normalized.csv
subject_column_name: 'participant_id'
cutout_mask_path:
cutin_mask_path: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.i.-S.T.s.-S.T.pol./mask/Rmask.npy
flip_dataset: False
input_size: (1, 33, 63, 56)